version: '3.4'

services:
  jwt_lista_compras:
    image: ${DOCKER_REGISTRY-}jwtlistacompras
    container_name: ListaCompras
    build:
      context: .
      dockerfile: Jwt_Lista_Compras/Dockerfile
    depends_on: 
      - database-ms-sql-server
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database-ms-sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssqldb
    ports:
      - "1433:1433"
    expose: 
      - 8080
    restart: always
    environment: 
      Anderson_PASSWORD: "123456"

volumes:
  db-volume:

